import React, {useRef, useState} from 'react';
import { createRoot } from 'react-dom/client';
import { motion, AnimatePresence } from 'framer-motion';
import {Upload, ScanLine, ShieldCheck, AlertTriangle, MapPin, ChevronRight, Orbit, Crosshair, Sparkles, CheckCircle2, Activity} from 'lucide-react';
import './style.css';

const API = 'http://127.0.0.1:8000';
const stages = ['Acquire Image','Enhance Terrain','Detect Hazards','Estimate Uncertainty','Calculate Safety','Rank Landing Zones'];
const stageIcons = [Upload, Sparkles, ScanLine, Activity, ShieldCheck, MapPin];

function Gauge({score}) { const dash=339.3, progress=dash*(1-score/100); return <div className="gauge"><svg viewBox="0 0 140 140"><circle cx="70" cy="70" r="54" className="gauge-bg"/><circle cx="70" cy="70" r="54" className="gauge-value" strokeDasharray={dash} strokeDashoffset={progress}/></svg><div><b>{score}</b><small>/ 100</small><span>SAFETY SCORE</span></div></div> }
function ImagePanel({title, src, label}) { return <article className="image-panel"><div className="panel-head"><span>{title}</span><em>{label}</em></div><img src={src} alt={title}/></article> }
function App(){
 const [file,setFile]=useState(null), [preview,setPreview]=useState(null), [loading,setLoading]=useState(false), [stage,setStage]=useState(-1), [result,setResult]=useState(null), [error,setError]=useState(''), [status,setStatus]=useState(''); const input=useRef();
 const select=(f)=>{if(!f)return; setFile(f);setPreview(URL.createObjectURL(f));setResult(null);setError('');setStatus(`Ready: ${f.name}`)};
 const analyze=async()=>{if(!file)return;setLoading(true);setResult(null);setError('');setStatus('Uploading image and running terrain assessment…');setStage(0); let step=0;const ticker=setInterval(()=>{step=Math.min(5,step+1);setStage(step)},550);try{const fd=new FormData();fd.append('file',file);const r=await fetch(`${API}/api/analyze`,{method:'POST',body:fd});if(!r.ok){const body=await r.json().catch(()=>({}));throw new Error(body.detail||`Analysis failed (HTTP ${r.status})`)}const data=await r.json();clearInterval(ticker);setStage(5);setResult(data);setStatus(`Assessment complete — Safety Score ${data.safety_score}/100.`)}catch(e){clearInterval(ticker);setStatus('');setError(`${e.message} Check that the FastAPI server is available at ${API}.`)}finally{setLoading(false)}};
 return <main><div className="stars"/><nav><div className="brand"><span className="brand-mark"><Orbit size={20}/></span><span>LUNA<span>SAFE</span><i>AI</i></span></div><div className="nav-meta"><span className="live"><i/> PROTOTYPE ONLINE</span><span>MISSION INTELLIGENCE / v0.1</span></div></nav>
 <section className="hero"><div className="eyebrow"><span/> LUNAR LANDING INTELLIGENCE</div><h1>See the terrain.<br/><strong>Choose the safe path.</strong></h1><p>Explainable computer-vision screening for lunar landing-site concepts — built for mission review, not autonomous flight.</p><div className="hero-rule"><span>01</span><div/><span>SURFACE RISK ASSESSMENT</span></div></section>
 {!result && <section className="workspace"><div className="upload-card"><div className="upload-copy"><div className="section-tag">INPUT / LUNAR SURFACE IMAGE</div><h2>Initialize terrain scan</h2><p>Upload an orbital, descent, or simulated lunar surface image to generate an interpretable landing-risk assessment.</p></div><div className={'dropzone '+(preview?'has-file':'')} onClick={()=>input.current.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();select(e.dataTransfer.files[0])}}>{preview?<><img src={preview}/><div className="file-overlay"><CheckCircle2/> {file.name}</div></>:<><div className="upload-icon"><Upload/></div><b>Drop lunar image here</b><span>PNG, JPG, TIFF · max 20 MB</span><button type="button">Browse files <ChevronRight size={15}/></button></>}<input ref={input} type="file" accept="image/*" onChange={e=>select(e.target.files[0])}/></div>{file&&<button className="analyze" onClick={analyze} disabled={loading}>{loading?<><ScanLine className="spin"/> ANALYZING SURFACE</>:<><Crosshair/> RUN LANDING ANALYSIS</>}</button>}{status&&<div className={'status '+(loading?'processing':'success')}><Activity size={14}/>{status}</div>}{error&&<div className="error">{error}</div>}</div>
 <div className="pipeline"><div className="section-tag">ANALYSIS PIPELINE</div>{stages.map((s,i)=>{const Icon=stageIcons[i];return <div className={'stage '+(stage>=i?'active':'')} key={s}><span><Icon size={17}/></span><div><b>{s}</b><small>{i===1?'Prototype SR fallback':i===2||i===3?'Prototype heuristics':'Explainable scoring'}</small></div>{stage>i?<CheckCircle2 size={16}/>:<i/>}</div>})}</div></section>}
 <AnimatePresence>{result&&<motion.section className="results" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}}><header className="results-head"><div><div className="section-tag">ASSESSMENT COMPLETE / SAFETY SCORE {result.safety_score}/100</div><h2>Landing-site intelligence brief</h2></div><button className="ghost" onClick={()=>{setResult(null);setFile(null);setPreview(null)}}>NEW SCAN</button></header><div className="readiness"><div className="ready-icon"><ShieldCheck/></div><div><span>MISSION READINESS · SCORE {result.safety_score}/100</span><b>{result.mission_readiness}</b></div><p>{result.readiness_note}</p><div className="status-dot"/></div>
 <div className="visual-grid"><ImagePanel title="ORIGINAL CAPTURE" src={result.images.original} label="INPUT"/><ImagePanel title="ENHANCED TERRAIN" src={result.images.enhanced} label="PROTOTYPE SR FALLBACK"/><ImagePanel title="UNCERTAINTY FIELD" src={result.images.uncertainty} label="HEURISTIC"/><ImagePanel title="FUSED HAZARD MAP" src={result.images.hazard_map} label="RISK COMPOSITE"/></div>
 <div className="insights"><article className="score-card"><div><div className="section-tag">SITE SAFETY INDEX</div><h3>Surface viability</h3><p className="prototype-label">PROTOTYPE / HEURISTIC ASSESSMENT</p><p>Risk-weighted score from shadows, crater candidates, roughness, slope proxy and image uncertainty.</p></div><Gauge score={result.safety_score}/></article><article className="hazards"><div className="section-tag">HAZARD INVENTORY</div><div className="hazard-grid">{Object.entries(result.hazard_summary).map(([name,v])=><div key={name}><span>{name.replace('_',' ')}</span><b>{v.value}<small>{v.unit}</small></b><i style={{width:`${v.percent}%`}}/></div>)}</div></article></div>
 <section className="zones"><div className="zone-intro"><div className="section-tag">RECOMMENDED LANDING WINDOWS</div><h2>Top ranked zones</h2><p>Square regions are selected by lowest mean fused hazard; spatial separation keeps alternatives meaningful.</p></div><div className="zone-list">{result.landing_zones.map((z,i)=><article className="zone" key={z.id}><div className="rank">0{i+1}</div><div className="zone-main"><b>{z.id}</b><span>{z.location} · {z.size_px}px window</span></div><div className="zone-score"><b>{z.score}</b><span>safety</span></div><div className="zone-risk"><span>RISK</span><b>{z.risk}%</b></div></article>)}</div></section>
 <section className="why"><div className="why-icon"><MapPin/></div><div><div className="section-tag">WHY THIS ZONE?</div><h3>{result.explanation.title}</h3><p>{result.explanation.text}</p></div><div className="metrics">{result.explanation.metrics.map(m=><span key={m}>{m}</span>)}</div></section></motion.section>}</AnimatePresence>
 <footer><AlertTriangle size={14}/> RESEARCH PROTOTYPE — NOT FLIGHT-QUALIFIED NAVIGATION SOFTWARE. RESULTS ARE IMAGE-BASED HEURISTICS, NOT TRAINED-MODEL OR REAL-WORLD SAFETY VALIDATION.</footer></main> }
createRoot(document.getElementById('root')).render(<App/>);
